#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="/home/ubuntu/KORStockScan"
PYTHON_BIN="$PROJECT_DIR/.venv/bin/python"
PROFILE="${1:-}"
INTERVAL_SEC="2"

case "$PROFILE" in
  samsung_heavy_midday)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SAMSUNG_HEAVY_MIDDAY_ENABLED=true
    CONFIRM="010140_MIDDAY_TWO_LEG_LIVE"
    ;;
  samsung_heavy_afternoon)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SAMSUNG_HEAVY_AFTERNOON_ENABLED=true
    CONFIRM="010140_AFTERNOON_TWO_LEG_LIVE"
    ;;
  sk_eternix_midday)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SK_ETERNIX_MIDDAY_ENABLED=true
    CONFIRM="475150_MIDDAY_TWO_LEG_LIVE"
    ;;
  mirae_asset_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_MIRAE_ASSET_MORNING_ENABLED=true
    CONFIRM="006800_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  jeju_semiconductor_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_JEJU_SEMICONDUCTOR_MORNING_ENABLED=true
    CONFIRM="080220_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  doosan_enerbility_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_DOOSAN_ENERBILITY_MORNING_ENABLED=true
    CONFIRM="034020_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  hanwha_ocean_late_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_HANWHA_OCEAN_LATE_MORNING_ENABLED=true
    CONFIRM="042660_LATE_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  kakao_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_KAKAO_MORNING_ENABLED=true
    CONFIRM="035720_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  kepco_afternoon)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_KEPCO_AFTERNOON_ENABLED=true
    CONFIRM="015760_AFTERNOON_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  kakao_late_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_KAKAO_LATE_MORNING_ENABLED=true
    CONFIRM="035720_LATE_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  sk_eternix_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SK_ETERNIX_MORNING_ENABLED=true
    CONFIRM="475150_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  mirae_asset_midday)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_MIRAE_ASSET_MIDDAY_ENABLED=true
    CONFIRM="006800_MIDDAY_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  sk_eternix_afternoon)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SK_ETERNIX_AFTERNOON_ENABLED=true
    CONFIRM="475150_AFTERNOON_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  samsung_heavy_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SAMSUNG_HEAVY_MORNING_ENABLED=true
    CONFIRM="010140_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  doosan_enerbility_late_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_DOOSAN_ENERBILITY_LATE_MORNING_ENABLED=true
    CONFIRM="034020_LATE_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  kakao_midday)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_KAKAO_MIDDAY_ENABLED=true
    CONFIRM="035720_MIDDAY_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  sk_telecom_afternoon)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SK_TELECOM_AFTERNOON_ENABLED=true
    CONFIRM="017670_AFTERNOON_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  samsung_ea_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SAMSUNG_EA_MORNING_ENABLED=true
    CONFIRM="028050_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  samsung_ea_late_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SAMSUNG_EA_LATE_MORNING_ENABLED=true
    CONFIRM="028050_LATE_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  samsung_ea_afternoon)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SAMSUNG_EA_AFTERNOON_ENABLED=true
    CONFIRM="028050_AFTERNOON_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  sk_telecom_late_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SK_TELECOM_LATE_MORNING_ENABLED=true
    CONFIRM="017670_LATE_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  sk_telecom_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SK_TELECOM_MORNING_ENABLED=true
    CONFIRM="017670_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  hanse_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_HANSE_MORNING_ENABLED=true
    CONFIRM="105630_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  hanse_afternoon)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_HANSE_AFTERNOON_ENABLED=true
    CONFIRM="105630_AFTERNOON_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  cj_cgv_midday)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_CJ_CGV_MIDDAY_ENABLED=true
    CONFIRM="079160_MIDDAY_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  cj_cgv_afternoon)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_CJ_CGV_AFTERNOON_ENABLED=true
    CONFIRM="079160_AFTERNOON_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  tym_midday)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_TYM_MIDDAY_ENABLED=true
    CONFIRM="002900_MIDDAY_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  tym_afternoon)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_TYM_AFTERNOON_ENABLED=true
    CONFIRM="002900_AFTERNOON_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  cj_cgv_late_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_CJ_CGV_LATE_MORNING_ENABLED=true
    CONFIRM="079160_LATE_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  kepco_late_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_KEPCO_LATE_MORNING_ENABLED=true
    CONFIRM="015760_LATE_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  kepco_midday)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_KEPCO_MIDDAY_ENABLED=true
    CONFIRM="015760_MIDDAY_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  hanse_late_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_HANSE_LATE_MORNING_ENABLED=true
    CONFIRM="105630_LATE_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  hanse_midday)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_HANSE_MIDDAY_ENABLED=true
    CONFIRM="105630_MIDDAY_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  nhn_afternoon)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_NHN_AFTERNOON_ENABLED=true
    CONFIRM="181710_AFTERNOON_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  youngone_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_YOUNGONE_MORNING_ENABLED=true
    CONFIRM="111770_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  youngone_afternoon)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_YOUNGONE_AFTERNOON_ENABLED=true
    CONFIRM="111770_AFTERNOON_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  sk_eternix_late_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SK_ETERNIX_LATE_MORNING_ENABLED=true
    CONFIRM="475150_LATE_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  mirae_asset_late_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_MIRAE_ASSET_LATE_MORNING_ENABLED=true
    CONFIRM="006800_LATE_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  kepco_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_KEPCO_MORNING_ENABLED=true
    CONFIRM="015760_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  nhn_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_NHN_MORNING_ENABLED=true
    CONFIRM="181710_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  nhn_late_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_NHN_LATE_MORNING_ENABLED=true
    CONFIRM="181710_LATE_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  sd_biosensor_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SD_BIOSENSOR_MORNING_ENABLED=true
    CONFIRM="137310_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  sd_biosensor_late_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SD_BIOSENSOR_LATE_MORNING_ENABLED=true
    CONFIRM="137310_LATE_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  sd_biosensor_midday)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SD_BIOSENSOR_MIDDAY_ENABLED=true
    CONFIRM="137310_MIDDAY_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  doosan_enerbility_afternoon)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_DOOSAN_ENERBILITY_AFTERNOON_ENABLED=true
    CONFIRM="034020_AFTERNOON_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  samsung_ea_midday)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SAMSUNG_EA_MIDDAY_ENABLED=true
    CONFIRM="028050_MIDDAY_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  fan_ocean_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_FAN_OCEAN_MORNING_ENABLED=true
    CONFIRM="028670_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  fan_ocean_late_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_FAN_OCEAN_LATE_MORNING_ENABLED=true
    CONFIRM="028670_LATE_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  *)
    echo "unsupported low-price two-leg profile: $PROFILE" >&2
    exit 2
    ;;
esac

exec env PYTHONPATH="$PROJECT_DIR" "$PYTHON_BIN" -m \
  src.trading.low_price_two_leg.service \
  --profile "$PROFILE" \
  --live \
  --confirm "$CONFIRM" \
  --interval-sec "$INTERVAL_SEC"
