#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="${PROJECT_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"
TARGET_DATE="${1:-$(TZ=Asia/Seoul date +%F)}"
# shellcheck source=cpu_affinity_profile.sh
. "$SCRIPT_DIR/cpu_affinity_profile.sh"
CPU_AFFINITY="${MONITOR_SNAPSHOT_CPU_AFFINITY:-$(korstockscan_default_cpu_affinity monitor)}"

# BUY drought 중간점검(장중)에서 스토리지 I/O burst 완화를 위한 경량 실행 프로필.
MONITOR_SNAPSHOT_PROFILE="${MONITOR_SNAPSHOT_PROFILE:-intraday_light}" \
MONITOR_SNAPSHOT_IO_DELAY_SEC="${MONITOR_SNAPSHOT_IO_DELAY_SEC:-1.2}" \
MONITOR_SNAPSHOT_START_JITTER_SEC="${MONITOR_SNAPSHOT_START_JITTER_SEC:-45}" \
MONITOR_SNAPSHOT_COOLDOWN_SEC="${MONITOR_SNAPSHOT_COOLDOWN_SEC:-60}" \
MONITOR_SNAPSHOT_INTRADAY_TREND_MAX_DATES="${MONITOR_SNAPSHOT_INTRADAY_TREND_MAX_DATES:-5}" \
MONITOR_SNAPSHOT_NOTIFY_ONLY="${MONITOR_SNAPSHOT_NOTIFY_ONLY:-1}" \
MONITOR_SNAPSHOT_ASYNC="${MONITOR_SNAPSHOT_ASYNC:-1}" \
MONITOR_SNAPSHOT_IONICE_CLASS="${MONITOR_SNAPSHOT_IONICE_CLASS:-2}" \
MONITOR_SNAPSHOT_IONICE_LEVEL="${MONITOR_SNAPSHOT_IONICE_LEVEL:-7}" \
MONITOR_SNAPSHOT_NICE_LEVEL="${MONITOR_SNAPSHOT_NICE_LEVEL:-12}" \
MONITOR_SNAPSHOT_CPU_AFFINITY="$CPU_AFFINITY" \
"$PROJECT_DIR/deploy/run_monitor_snapshot_safe.sh" "$TARGET_DATE"
