from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any


class LatencyState(str, Enum):
    """System health bucket for entry timing."""

    SAFE = "SAFE"
    CAUTION = "CAUTION"
    DANGER = "DANGER"


class EntryDecision(str, Enum):
    """Policy output for a candidate entry."""

    ALLOW_NORMAL = "ALLOW_NORMAL"
    REJECT_TIMEOUT = "REJECT_TIMEOUT"
    REJECT_SLIPPAGE = "REJECT_SLIPPAGE"
    REJECT_DANGER = "REJECT_DANGER"
    REJECT_MARKET_CONDITION = "REJECT_MARKET_CONDITION"


@dataclass(slots=True)
class SignalSnapshot:
    """Immutable signal-time reference data for entry validation."""

    symbol: str
    strategy_id: str
    signal_time: datetime
    signal_price: int
    signal_strength: float
    planned_qty: int
    side: str
    context: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class LatencyStatus:
    """Measured websocket and order-path health at entry time."""

    state: LatencyState
    ws_age_ms: int
    ws_jitter_ms: int
    order_rtt_avg_ms: int
    order_rtt_p95_ms: int
    quote_stale: bool
    spread_ratio: float

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class PolicyResult:
    """Final policy verdict prior to order generation."""

    decision: EntryDecision
    reason: str
    computed_allowed_slippage: int
    computed_deadline_ms: int
    latest_price: int

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class PlannedOrder:
    """A broker-ready order plan generated by an entry mode."""

    symbol: str
    side: str
    qty: int
    price: int
    order_type: str
    tif: str
    tag: str

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)
